service: autoinvoicer

provider:
  name: aws
  runtime: nodejs8.10

functions:
  graphql:
    handler: index.sls
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: welcome
          method: post
          cors: true
      - http:
          path: password-reset
          method: post
          cors: true

plugins:
  - serverless-offline
