service: autoinvoicer

provider:
  name: aws
  runtime: nodejs8.10

functions:
  graphql:
    handler: index.sls
    events:
      - http:
          path: auth/google
          method: get
          cors: true
      - http:
          path: auth/google/home
          method: get
          cors: true
      - http:
          path: auth/facebook
          method: get
          cors: true
      - http:
          path: auth/facebook/home
          method: get
          cors: true
      - http:
          path: auth/stripe
          method: get
          cors: true
      - http:
          path: auth/stripe/home
          method: get
          cors: true
      - http:
          path: stripe/charge
          method: post
          cors: true
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: welcome
          method: post
          cors: true
      - http:
          path: password-reset
          method: post
          cors: true
      - http:
          path: taxes/{zip}
          method: get
          cors: true
          request:
            parameters:
              paths:
                zip: true

plugins:
  - serverless-offline
